spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/nucacolatest
    username: root
    password: Telran2023

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

